#!/bin/bash

file=`cat $1`
fi
COMMIT_REGEX='^(fixup! )*?(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z ]+\))?: .+$'
if ! grep -qE "$COMMIT_REGEX" "$1"; then
  echo 'Invalid commit message, aborting... See https://www.conventionalcommits.org/en/v1.0.0/#summary' >&2
  exit 1
fi
